<script>
export default {
  data() {
    return {
      footerFirstNav: [
        {
          text: 'Domande frequenti',
          url: '#',
        },
        {
          text: 'Rapporti con gli investitori',
          url: '#',
        },
        {
          text: 'Come guardare Netflix',
          url: '#',
        },
        {
          text: "Informazioni sull'azienda",
          url: '#',
        },
        {
          text: 'Note legali',
          url: '#',
        },
      ],
      footerSecondNav: [
        {
          text: 'Centro assistenza',
          url: '#',
        },
        {
          text: 'Opportunità di lavoro',
          url: '#',
        },
        {
          text: 'Condizioni di utilizzo',
          url: '#',
        },
        {
          text: 'Contattaci',
          url: '#',
        },
        {
          text: 'Solo su Netflix',
          url: '#',
        },
      ],
      footerThirdNav: [
        {
          text: 'Account',
          url: '#',
        },
        {
          text: 'Riscatta carte regalo',
          url: '#',
        },
        {
          text: 'Privacy',
          url: '#',
        },
        {
          text: 'Test di velocità',
          url: '#',
        },
      ],
      footerForthNav: [
        {
          text: 'Media Center',
          url: '#',
        },
        {
          text: 'Acquista carte regalo',
          url: '#',
        },
        {
          text: 'Preferenze per i cookie',
          url: '#',
        },
        {
          text: 'Garanzia legale',
          url: '#',
        },
      ],
    }
  },
}
</script>

<template>
  <section>
    <div class="number">
      Domande? Chiama 800-130-364
    </div>
    <div class="container-box container">
      <nav>
        <!-- generate a list of links with headings for each item in the footerFirstNav array -->
        <ul>
          <!--li elements being dynamically generated by using v-for to loop through an array of footerFirstNav items -->
          <li v-for="(link, index) in footerFirstNav" :key="index">
            <!-- href being dynamically bound to the url property of the current link item in the array, its text content being set to the value of the text property -->
            <a :href="link.url">
              {{ link.text }}
            </a>
          </li>
        </ul>
      </nav>
      <nav>
        <ul>
          <li v-for="(link, index) in footerSecondNav" :key="index">
            <a :href="link.url">
              {{ link.text }}
            </a>
          </li>
        </ul>
      </nav>
      <nav>
        <ul>
          <li v-for="(link, index) in footerThirdNav" :key="index">
            <a :href="link.url">
              {{ link.text }}
            </a>
          </li>
        </ul>
      </nav>
      <nav>
        <ul>
          <li v-for="(link, index) in footerForthNav" :key="index">
            <a :href="link.url">
              {{ link.text }}
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </section>
</template>


<style lang="scss" scoped>
@use '../styles/general.scss' as *;
@use '../styles/partials/mixins.scss' as *;
@use '../styles/partials/variables' as *;

section {
  background-color: black;

  .number {
    text-align: center;
    color: #737373;
    padding-bottom: 20px;
    font-size: 1em;
  }

  ul li {
    list-style-type: none;

    a {
      color: #737373;
      text-decoration: none;
      font-size: 13px;

      &:hover {
        text-decoration: underline;
      }
    }
  }
}

.container-box {
  padding-bottom: 50px;
  justify-content: center;
  max-width: 1100px;
  display: flex;
  gap: 5em;
}
</style>
